### ISSUE TITLE
Unable to valiadte any FHIR response getting "Error loading /root/.fhir/packages/hl7.fhir.r5.core#4.6.0/package/StructureDefinition-Account.json: Unknown FHIRVersion code '4.6.0' on line 1"

### ISSUE THREAD

**Issue by amruthkavadi** [inferno-community/fhir-validator-app#54] opened 2021-05-19 14:50 UTC
Pick an Implementation Guide to validate against:
hl7.fhir.us.core

Profile:
Patient

Note: Same error is getting displayed for all profiles

**Comment by radamson** [comment] 2021-05-19 15:29
Are you running the app locally or on a hosted instance (e.g. inferno.healthit.gov/validator)

**Comment by amruthkavadi** [comment] 2021-05-19 15:40
Hi,

We are running using *inferno.healthit.gov/validator
<http://inferno.healthit.gov/validator>*

Thanks,
Amruth Raj

**Comment by radamson** [comment] 2021-05-19 16:42
A change in the upstream package server (https://packages.fhir.org) caused a regression which made older versions of the library stop working. We've updated the deployed instance and the problem should be fixed now.

Can you give it another try and confirm that the issue is resolved so we can close this issue?

**Comment by radamson** [comment] 2021-05-19 18:19
Going to close this issue since it appears to be resolved. @amruthkavadi feel free to reopen if you're still having problems.

**Closed by radamson** 2021-05-19 18:19 UTC
